language: node_js
node_js:
  - "8"
install:
    - npm install -g gitbook-cli
    - gitbook install
    - gitbook build
script:
    - travis_wait 1000 gitbook build
    - echo "go.wuhaolin.cn" > _book/CNAME
deploy:
  provider: pages
  local-dir: ./_book
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master